### ISSUE TITLE
README issues

### ISSUE THREAD

**Issue by tleb** [jacksleight/coast#15]
Was browsing this project, and I saw a few mistakes on the README:

* **Hello World** section: it shows the use of `Coast\Request` and `Coast\Response`, but the doc shows different ([`Coast\App\Request`](https://rawgit.com/jacksleight/coast/docs/class-Coast.App.Request.html) and [`Coast\App\Response`](https://rawgit.com/jacksleight/coast/docs/class-Coast.App.Response.html)).
* **Documentation** section: ~~exammples~~ examples.

This looks like a nice project, I am probably going to try it. :)

**Comment by jacksleight** [comment]
Well spotted, thanks! I have fixed the typo in README and updated the documentation (which was very out of date). I have also added a bit more information to the README, listing all of the components that currently exist.

If you have any other feedback or suggestions they're very welcome. As you can probably see the documentation and examples are a work in progress, but if you need any help or would like an example of how to use something in particular just shout.
